from __future__ import annotations

"""
Prebuilt script: config_drift_report.py

Compares the two most recent backup files per switch (generated by
backup_switch.py) and reports whether configuration drift has occurred.

This is a simple text-based comparison intended for lab/small environments.
For larger deployments you would typically integrate with a dedicated
config management tool.
"""

import difflib
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Tuple


async def run(ctx: Any) -> Dict[str, Any]:
    """
    Generate a config drift report based on /data/backups.

    Assumes backup filenames follow the pattern:
      <hostname-or-ip>-YYYYMMDD-HHMMSS.cfg

    Returns
    -------
    dict containing per-device drift status and optional diff excerpts.
    """
    backups_dir = Path("/data/backups")
    if not backups_dir.exists():
        ctx.logger("config_drift_report: backups directory does not exist")
        return {"status": "no_backups", "devices": []}

    # Group backups by device prefix (everything before the first timestamp dash).
    files_by_device: Dict[str, List[Path]] = defaultdict(list)
    for path in backups_dir.glob("*.cfg"):
        name = path.name
        if "-" not in name:
            continue
        # Device label is everything up to last timestamp block.
        # Example: gw-01-20231205-120000.cfg -> device_label="gw-01"
        parts = name.split("-")
        if len(parts) < 3:
            continue
        device_label = "-".join(parts[:-2])
        files_by_device[device_label].append(path)

    report: List[Dict[str, Any]] = []

    for device_label, paths in files_by_device.items():
        if len(paths) < 2:
            ctx.logger(f"config_drift_report: only one backup for {device_label}, skipping")
            continue

        # Sort by timestamp inferred from filename (best-effort).
        def _parse_ts(p: Path) -> datetime:
            try:
                # Last two dash-separated parts make up YYYYMMDD-HHMMSS
                base = p.name.rsplit(".", 1)[0]
                parts = base.split("-")
                ts_str = "-".join(parts[-2:])
                return datetime.strptime(ts_str, "%Y%m%d-%H%M%S")
            except Exception:
                return datetime.min

        paths_sorted = sorted(paths, key=_parse_ts)
        older, newer = paths_sorted[-2], paths_sorted[-1]

        old_text = older.read_text(errors="ignore").splitlines()
        new_text = newer.read_text(errors="ignore").splitlines()

        if old_text == new_text:
            ctx.logger(f"config_drift_report: no drift for {device_label}")
            report.append(
                {
                    "device": device_label,
                    "status": "no_drift",
                    "older": str(older),
                    "newer": str(newer),
                }
            )
            continue

        ctx.logger(f"config_drift_report: drift detected for {device_label}")
        diff_lines = list(
            difflib.unified_diff(
                old_text,
                new_text,
                fromfile=str(older),
                tofile=str(newer),
                n=5,
            )
        )

        # Store only first N lines of diff for brevity.
        excerpt = "\n".join(diff_lines[:200])

        report.append(
            {
                "device": device_label,
                "status": "drift",
                "older": str(older),
                "newer": str(newer),
                "diff_excerpt": excerpt,
            }
        )

    return {
        "status": "ok",
        "devices": report,
    }