-- NetPulse Phase 7: SNMP router polling tables
--
-- Adds tables introduced in:
--   - app/models/router.py
--
-- PostgreSQL.

BEGIN;

CREATE TABLE IF NOT EXISTS routers (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id    INTEGER NOT NULL,
    host         VARCHAR(255) NOT NULL,
    snmp_version VARCHAR(8) NOT NULL DEFAULT '2c',
    community    VARCHAR(255) NULL,
    port         INTEGER NOT NULL DEFAULT 161,
    if_indexes   JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_routers_device_id FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT uq_routers_device_id UNIQUE (device_id)
);

CREATE INDEX IF NOT EXISTS ix_routers_device_id ON routers (device_id);
CREATE INDEX IF NOT EXISTS ix_routers_host ON routers (host);

CREATE TABLE IF NOT EXISTS router_interface_counters (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    router_id      INTEGER NOT NULL,
    if_index       INTEGER NOT NULL,
    if_descr       VARCHAR(255) NULL,
    in_octets      BIGINT NOT NULL,
    out_octets     BIGINT NOT NULL,
    last_polled_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_router_interface_counters_router_id FOREIGN KEY (router_id) REFERENCES routers(id) ON DELETE CASCADE,
    CONSTRAINT uq_router_interface_counters_router_id_if_index UNIQUE (router_id, if_index)
);

CREATE INDEX IF NOT EXISTS ix_router_interface_counters_router_id ON router_interface_counters (router_id);
CREATE INDEX IF NOT EXISTS ix_router_interface_counters_if_index ON router_interface_counters (if_index);
CREATE INDEX IF NOT EXISTS ix_router_interface_counters_last_polled_at ON router_interface_counters (last_polled_at);

COMMIT;
