-- NetPulse Phase 5: PCAP metadata tables
--
-- This migration adds the tables introduced in app/models/pcap_meta.py:
--   - pcap_files
--   - pcap_packets
--
-- It is written for PostgreSQL.
--
-- Safe to re-run: uses IF NOT EXISTS guards for tables/indexes.

BEGIN;

CREATE TABLE IF NOT EXISTS pcap_files (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capture_id        INTEGER NULL,

    filename          VARCHAR(255) NOT NULL,
    filepath          VARCHAR(1024) NOT NULL,

    interface         VARCHAR(64) NULL,
    bpf_filter        TEXT NULL,

    file_size_bytes   INTEGER NOT NULL DEFAULT 0,
    packet_count      INTEGER NOT NULL DEFAULT 0,

    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    captured_started_at   TIMESTAMP WITHOUT TIME ZONE NULL,
    captured_finished_at  TIMESTAMP WITHOUT TIME ZONE NULL,

    indexed_at        TIMESTAMP WITHOUT TIME ZONE NULL,
    index_error       TEXT NULL,

    CONSTRAINT uq_pcap_files_filepath UNIQUE (filepath),
    CONSTRAINT fk_pcap_files_capture_id
        FOREIGN KEY (capture_id) REFERENCES packet_captures(id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_pcap_files_capture_id ON pcap_files (capture_id);


CREATE TABLE IF NOT EXISTS pcap_packets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    file_id       INTEGER NOT NULL,
    packet_index  INTEGER NOT NULL,
    timestamp     TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    src_ip        VARCHAR(45) NULL,
    dst_ip        VARCHAR(45) NULL,
    src_port      INTEGER NULL,
    dst_port      INTEGER NULL,
    protocol      VARCHAR(16) NULL,

    length        INTEGER NOT NULL DEFAULT 0,
    info          TEXT NULL,

    CONSTRAINT fk_pcap_packets_file_id
        FOREIGN KEY (file_id) REFERENCES pcap_files(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_pcap_packets_file_id ON pcap_packets (file_id);
CREATE INDEX IF NOT EXISTS ix_pcap_packets_file_packet_index ON pcap_packets (file_id, packet_index);
CREATE INDEX IF NOT EXISTS ix_pcap_packets_timestamp_brin ON pcap_packets USING brin (timestamp);

COMMIT;
