-- NetPulse Phase 6: Router config baseline table
--
-- Adds table introduced in app/models/router_config_baseline.py
--
-- PostgreSQL.

BEGIN;

CREATE TABLE IF NOT EXISTS router_config_baselines (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host          VARCHAR(255) NOT NULL,
    driver        VARCHAR(32) NOT NULL,
    username      VARCHAR(255) NOT NULL,
    port          INTEGER NULL,
    config_hash   VARCHAR(64) NOT NULL,
    last_seen_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_router_config_baseline_host_driver_username_port
        UNIQUE (host, driver, username, port)
);

CREATE INDEX IF NOT EXISTS ix_router_config_baselines_host ON router_config_baselines (host);
CREATE INDEX IF NOT EXISTS ix_router_config_baselines_driver ON router_config_baselines (driver);
CREATE INDEX IF NOT EXISTS ix_router_config_baselines_username ON router_config_baselines (username);
CREATE INDEX IF NOT EXISTS ix_router_config_baselines_last_seen_at ON router_config_baselines (last_seen_at);

COMMIT;
